os: osx
osx_image: xcode9

language: rust
rust: stable

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Hexe"

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document
  - cargo install cargo-lipo

script: ./Scripts/travis.sh
