os: osx
osx_image: xcode9

language: rust
rust: stable

cache: cargo

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Hexe"

install: ./Scripts/install.sh
script:  ./Scripts/travis.sh
